name: project_api
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter_html: ^2.2.1
  cupertino_icons: ^1.0.8
  http: ^1.3.0  # Versi terbaru yang kompatibel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
